/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upv.poo;

import edu.upv.poo.dataaccess.PersonaDao;
import edu.upv.poo.dbmodels.Persona;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;


public class ActualizarCliente extends javax.swing.JFrame {
    int currentSuperUsuario;
    
    int id = 0;
    public ActualizarCliente(int id,int usuario) {
        initComponents();
        
        this.id = id;
        this.llenarDatos();
        this.labelLlenar.setVisible(false);
        this.currentSuperUsuario = usuario;
    }
    
    private void llenarDatos(){
        Persona persona = new Persona();
                        try (
                Connection con = DbUtils.getConnection(); 
                Statement stmt = con.createStatement()) {
            PersonaDao personaDao = new PersonaDao(con);
            persona = personaDao.getById(this.id);
            
            this.editTextCorreo.setText(persona.getCorreoElectronico());
            this.editTextId.setText(String.valueOf(persona.getPersonaId()));
            this.editTextIdentificacion.setText(persona.getIdentificacion());
            this.editTextNumTarjeta.setText(persona.getNumTarjeta());
            this.editTextRfc.setText(persona.getRfc());
            
        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        editTextIdentificacion = new javax.swing.JTextField();
        editTextRfc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboTipoIdentificacion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editTextId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        editTextCorreo = new javax.swing.JTextField();
        editTextNumTarjeta = new javax.swing.JTextField();
        btnActualizarCliente = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        labelLlenar = new javax.swing.JLabel();
        btnEliminarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("ACTUALIZAR CLIENTE");

        jLabel6.setText("Número de tarjeta");

        jLabel7.setText("RFC");

        editTextRfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTextRfcActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de identificación");

        comboTipoIdentificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acta de nacimiento", "Pasaporte", "Visa" }));
        comboTipoIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoIdentificacionActionPerformed(evt);
            }
        });

        jLabel3.setText("Identificacion");

        jLabel5.setText("Número de cliente");

        editTextId.setEnabled(false);
        editTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTextIdActionPerformed(evt);
            }
        });

        jLabel4.setText("Correo Electrónico");

        editTextCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTextCorreoActionPerformed(evt);
            }
        });

        editTextNumTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTextNumTarjetaActionPerformed(evt);
            }
        });

        btnActualizarCliente.setText("Actualizar Cliente");
        btnActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClienteActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        labelLlenar.setForeground(new java.awt.Color(255, 0, 0));
        labelLlenar.setText("Porfavor llene todos los campos");

        btnEliminarCliente.setText("Eliminar Cliente");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editTextIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editTextRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editTextCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editTextNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editTextId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(btnActualizarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelLlenar)
                                    .addComponent(btnEliminarCliente)))
                            .addComponent(btnRegresar))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(editTextIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(editTextCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editTextNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editTextRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(editTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarCliente)
                    .addComponent(btnEliminarCliente))
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLlenar)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editTextRfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTextRfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTextRfcActionPerformed

    private void comboTipoIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoIdentificacionActionPerformed

    private void editTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTextIdActionPerformed

    private void editTextNumTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTextNumTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTextNumTarjetaActionPerformed

    private void btnActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClienteActionPerformed
        try (
            Connection con = DbUtils.getConnection();
            Statement stmt = con.createStatement()) {
            PersonaDao personaDao = new PersonaDao(con);

            Persona e = personaDao.getById(this.id);
            Persona e2 = e;
            
            String correo = this.editTextCorreo.getText();
            String identificacion = this.editTextIdentificacion.getText();
            String numTarjeta = this.editTextNumTarjeta.getText();
            String rfc = this.editTextRfc.getText();
            String tipoIdentificacion = this.comboTipoIdentificacion.getSelectedItem().toString();
            if (correo.isEmpty() == false && identificacion.isEmpty() == false && numTarjeta.isEmpty() == false && rfc.isEmpty() == false) {     

                                
                e2.setIdentificacion(identificacion);
                e2.setCorreoElectronico(correo);
                e2.setNumTarjeta(numTarjeta);
                e2.setRfc(rfc);
                e2.setTipoIdentificacion(tipoIdentificacion);
                
                personaDao.update(e2);
                
                this.labelLlenar.setVisible(false);

            }else{
                this.labelLlenar.setVisible(true);

            }

        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarClienteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ConsultarClientes consultar = new ConsultarClientes(this.currentSuperUsuario);
        consultar.show();
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void editTextCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTextCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTextCorreoActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        try (
            Connection con = DbUtils.getConnection();
            Statement stmt = con.createStatement()) {
            PersonaDao personaDao = new PersonaDao(con);
            
            if (this.editTextId.getText().isEmpty() == false){
                try{
                    personaDao.delete(this.id);
                    this.btnRegresarActionPerformed(evt);
                }catch(Exception e){
                    System.out.println(e);
                }
                
            }

        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboTipoIdentificacion;
    private javax.swing.JTextField editTextCorreo;
    private javax.swing.JTextField editTextId;
    private javax.swing.JTextField editTextIdentificacion;
    private javax.swing.JTextField editTextNumTarjeta;
    private javax.swing.JTextField editTextRfc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelLlenar;
    // End of variables declaration//GEN-END:variables
}
