/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upv.poo;

import edu.upv.poo.dataaccess.AutoDao;
import edu.upv.poo.dataaccess.PersonaDao;
import edu.upv.poo.dataaccess.PrestamoDao;
import edu.upv.poo.dbmodels.Auto;
import edu.upv.poo.dbmodels.Persona;
import edu.upv.poo.dbmodels.Prestamo;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Devolucion extends javax.swing.JFrame {

    /**
     * Creates new form Devolucion
     */
    private int idAuto;
    private int currentSuperUsuario;
    public Devolucion(int idAuto, int usuario) {
        initComponents();
        this.idAuto = idAuto;
        this.currentSuperUsuario = usuario;
        this.labelLlenar.setVisible(false);
        this.llenarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editTextMonto = new javax.swing.JTextField();
        btnPrestar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        spinnerFechaFinal = new javax.swing.JSpinner();
        spinnerFecha = new javax.swing.JSpinner();
        labelLlenar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboIdAuto = new javax.swing.JComboBox<>();
        comboIdCliente = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editTextLugarDeRenta = new javax.swing.JTextField();
        btnDevolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editTextMonto.setEnabled(false);
        editTextMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTextMontoActionPerformed(evt);
            }
        });

        btnPrestar.setText("Actualizar préstamo");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha de devolución esperada");

        spinnerFechaFinal.setModel(new javax.swing.SpinnerDateModel());
        spinnerFechaFinal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerFechaFinalStateChanged(evt);
            }
        });

        spinnerFecha.setModel(new javax.swing.SpinnerDateModel());
        spinnerFecha.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerFechaStateChanged(evt);
            }
        });

        labelLlenar.setForeground(new java.awt.Color(255, 0, 0));
        labelLlenar.setText("Porfavor llene todos los campos con valores adecuados");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("MODIFICA PRÉSTAMO");

        jLabel2.setText("Id del auto a prestar");

        jLabel3.setText("Id del cliente");

        jLabel4.setText("Fecha del préstamo");

        comboIdAuto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboIdAuto.setEnabled(false);
        comboIdAuto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboIdAutoItemStateChanged(evt);
            }
        });

        comboIdCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Lugar de renta");

        jLabel6.setText("Monto");

        btnDevolver.setText("Devolver auto");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLlenar)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(170, 170, 170))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editTextMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editTextLugarDeRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboIdAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnPrestar)
                        .addGap(18, 18, 18)
                        .addComponent(btnDevolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboIdAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(spinnerFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(editTextLugarDeRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editTextMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrestar)
                    .addComponent(btnDevolver))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLlenar)
                    .addComponent(btnRegresar))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editTextMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTextMontoActionPerformed

    }//GEN-LAST:event_editTextMontoActionPerformed

    private void llenarDatos() {
        this.comboIdAuto.removeAllItems();
        this.comboIdCliente.removeAllItems();
        try (
                
            Connection con = DbUtils.getConnection(); 
            Statement stmt = con.createStatement()) {
            
            
            
            AutoDao autoDao = new AutoDao(con);
            PrestamoDao prestamoDao = new PrestamoDao(con);
            PersonaDao personaDao = new PersonaDao(con);
            
            Prestamo prestamo = prestamoDao.getById(this.idAuto);
            
            Persona[] personas = personaDao.getAll();
            Auto[] autos = autoDao.getAll();
            edu.upv.poo.dbmodels.Prestamo[] prestamos = prestamoDao.getAll();
            
            for (Persona i: personas) {
                this.comboIdCliente.addItem(String.valueOf(i.getPersonaId()));
            }
            
            this.comboIdAuto.addItem(String.valueOf(prestamo.getIdAuto()));
            this.comboIdCliente.setSelectedItem(String.valueOf(prestamo.getIdCliente()));
            SimpleDateFormat DateForm = new SimpleDateFormat("yyyy-MM-dd");
            Date date1 = new Date();
            Date date2 = new Date();
            System.out.println(prestamo.getFechaRenta().toString());
            try {
                date1 = DateForm.parse(prestamo.getFechaRenta()); // Reemplaza "-0700" con la zona horaria correcta.
                date2 = DateForm.parse(prestamo.getFinalRenta()); // Reemplaza "-0700" con la zona horaria correcta.
            } catch (ParseException ex) {
                System.out.println(ex);
            }

            this.spinnerFecha.setValue(date1);
            this.spinnerFechaFinal.setValue(date2);
            this.editTextLugarDeRenta.setText(prestamo.getLugarDeRenta());
            
            
            
        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        }        
    }

    private void actualizarMonto(){
        Date date1 = (Date)this.spinnerFecha.getValue();
        Date date2 = (Date)this.spinnerFechaFinal.getValue();
        
        long diffInMillies = Math.abs(date2.getTime() - date1.getTime());
        long diff = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);
        
        try (
                
            Connection con = DbUtils.getConnection(); 
            Statement stmt = con.createStatement()) {
            
            AutoDao autoDao = new AutoDao(con);
            try{
                Auto auto = autoDao.getById(Integer.valueOf(this.comboIdAuto.getSelectedItem().toString()));
                double montoFinal = diff * auto.getRentaPorDia();
                this.editTextMonto.setText(String.valueOf(montoFinal));
            }catch(Exception e){
                
            }
            
        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        }       
    }
    
    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        try (
            Connection con = DbUtils.getConnection();
            Statement stmt = con.createStatement()) {
            PrestamoDao prestamoDao = new PrestamoDao(con);

            Prestamo prestamo = new Prestamo();

            int idAuto = Integer.valueOf(this.comboIdAuto.getSelectedItem().toString());
            int idCliente = Integer.valueOf(this.comboIdCliente.getSelectedItem().toString());
            SimpleDateFormat DateForm = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");

            String fechaPrestamo = DateForm.format(this.spinnerFecha.getValue());
            String fechaFinal = DateForm.format(this.spinnerFechaFinal.getValue());
            String lugar = this.editTextLugarDeRenta.getText();
            double monto = 0;
            try{
                monto = Double.valueOf(this.editTextMonto.getText());
            }catch (Exception e){
                monto = 0;
            }

            if (lugar.isEmpty() == false && monto > 0) {
                prestamo.setFechaRenta(fechaPrestamo);
                prestamo.setFinalRenta(fechaFinal);
                prestamo.setIdAuto(idAuto);
                prestamo.setIdCliente(idCliente);
                prestamo.setMonto(monto);
                prestamo.setLugarDeRenta(lugar);
                prestamoDao.update(prestamo);

            }else{
                this.labelLlenar.setVisible(true);

            }

        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        } catch (ParseException ex) {
            Logger.getLogger(Devolucion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Devoluciones main = new Devoluciones(this.currentSuperUsuario);
        main.show();
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void spinnerFechaFinalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerFechaFinalStateChanged
        this.actualizarMonto();
    }//GEN-LAST:event_spinnerFechaFinalStateChanged

    private void spinnerFechaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerFechaStateChanged

        this.actualizarMonto();
    }//GEN-LAST:event_spinnerFechaStateChanged

    private void comboIdAutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboIdAutoItemStateChanged
        this.actualizarMonto();
    }//GEN-LAST:event_comboIdAutoItemStateChanged

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
                try (
            Connection con = DbUtils.getConnection();
            Statement stmt = con.createStatement()) {
            PrestamoDao prestamoDao = new PrestamoDao(con);

            prestamoDao.delete(this.idAuto);
            this.btnRegresarActionPerformed(evt);

        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnDevolverActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboIdAuto;
    private javax.swing.JComboBox<String> comboIdCliente;
    private javax.swing.JTextField editTextLugarDeRenta;
    private javax.swing.JTextField editTextMonto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelLlenar;
    private javax.swing.JSpinner spinnerFecha;
    private javax.swing.JSpinner spinnerFechaFinal;
    // End of variables declaration//GEN-END:variables
}
