/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upv.poo;

import edu.upv.poo.dataaccess.AutoDao;
import edu.upv.poo.dataaccess.PersonaDao;
import edu.upv.poo.dataaccess.UsuarioDao;
import edu.upv.poo.dbmodels.Auto;
import edu.upv.poo.dbmodels.Usuario;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;


public class RegistrarAuto extends javax.swing.JFrame {

    public RegistrarAuto() {
        initComponents();
        this.setAutoId();
        this.labelLlenar.setVisible(false);
    }
    
    private void setAutoId(){
        
        try (
                Connection con = DbUtils.getConnection(); 
                Statement stmt = con.createStatement()) {
            AutoDao autoDao = new AutoDao(con);
            
            this.editTextId.setText(String.valueOf(autoDao.getLastId()));
            
        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        editTextModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        editTextColor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarAuto = new javax.swing.JButton();
        editTextMarca = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editTextId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        labelLlenar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        editTextRentaPorDia = new javax.swing.JTextField();
        editTextMatricula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        editTextObservaciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Modelo");

        jLabel6.setText("Observaciones");

        jLabel7.setText("Color");

        editTextColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTextColorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("REGISTRAR NUEVO AUTO");

        btnRegistrarAuto.setText("Registrar Auto");
        btnRegistrarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAutoActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel2.setText("Matrícula");

        jLabel5.setText("Número de auto");

        editTextId.setEnabled(false);
        editTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTextIdActionPerformed(evt);
            }
        });

        jLabel3.setText("Marca");

        labelLlenar.setForeground(new java.awt.Color(255, 0, 0));
        labelLlenar.setText("Porfavor llene todos los campos con valores adecuados");

        jLabel8.setText("Renta por día");

        editTextRentaPorDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTextRentaPorDiaActionPerformed(evt);
            }
        });

        editTextObservaciones.setColumns(20);
        editTextObservaciones.setRows(5);
        editTextObservaciones.setText("Ninguna");
        jScrollPane1.setViewportView(editTextObservaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelLlenar)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editTextColor)
                                    .addComponent(editTextId)
                                    .addComponent(editTextRentaPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(btnRegistrarAuto))
                            .addComponent(btnRegresar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(editTextMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(editTextModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(editTextMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(76, 76, 76)))
                        .addContainerGap(38, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(editTextMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(editTextMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(editTextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editTextRentaPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(editTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnRegistrarAuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar)
                .addGap(18, 18, 18)
                .addComponent(labelLlenar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editTextColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTextColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTextColorActionPerformed

    private void btnRegistrarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAutoActionPerformed
        try (
            Connection con = DbUtils.getConnection();
            Statement stmt = con.createStatement()) {
            AutoDao autoDao = new AutoDao(con);
            
            Auto e = new Auto();
            try{
                String matricula = this.editTextMatricula.getText();
                String marca = this.editTextMarca.getText();
                String modelo = this.editTextModelo.getText();
                String observaciones = this.editTextObservaciones.getText();
                String color = this.editTextColor.getText();
                double rentaPorDia = Double.valueOf(this.editTextRentaPorDia.getText());

                if (matricula.isEmpty() == false && marca.isEmpty() == false && modelo.isEmpty() == false && observaciones.isEmpty() == false && color.isEmpty() == false && rentaPorDia >= 0) {
                    e.setColor(color);
                    e.setMarca(marca);
                    e.setMatricula(matricula);
                    e.setModelo(modelo);
                    e.setObservaciones(observaciones);
                    e.setRentaPorDia(rentaPorDia);
                    
                    autoDao.insert(e);

                    this.setAutoId();
                    this.editTextModelo.setText("");
                    this.editTextMarca.setText("");
                    this.editTextObservaciones.setText("");
                    this.editTextColor.setText("");
                    this.editTextObservaciones.setText("Ninguna");
                    this.editTextRentaPorDia.setText("");
                    this.editTextMatricula.setText("");
                    
                    this.labelLlenar.setVisible(false);

                }else{
                    this.labelLlenar.setVisible(true);
                }
                
            }catch(Exception a){
                    
            }


        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarAutoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MainApp main = new MainApp(1);
        main.show();
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void editTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTextIdActionPerformed

    private void editTextRentaPorDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTextRentaPorDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTextRentaPorDiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarAuto;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField editTextColor;
    private javax.swing.JTextField editTextId;
    private javax.swing.JTextField editTextMarca;
    private javax.swing.JTextField editTextMatricula;
    private javax.swing.JTextField editTextModelo;
    private javax.swing.JTextArea editTextObservaciones;
    private javax.swing.JTextField editTextRentaPorDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelLlenar;
    // End of variables declaration//GEN-END:variables
}
